project:
  type: website
  output-dir: docs

website:
  title: "Helena M. Garcia"
  navbar:
    left:
      - href: index.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

